export const SET_SORT_BY = 'SET_SORT_BY'
export const SET_CATEGORY = 'SET_CATEGORY'
export const SET_PIZZAS = 'SET_PIZZAS'
export const SET_LOADED = 'SET_LOADED'
export const SET_LOADING = 'SET_LOADING'
export const ADD_PIZZA_CART = 'ADD_PIZZA_CART'
